// Code generated by goctl. DO NOT EDIT!
// Source: sysuser.proto

package systemuser

import (
	"context"

	"github.com/zhaoqiang0201/zero-vue-admin/server/usercenter/rpc/system/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	LoginRequest  = pb.LoginRequest
	LoginResponse = pb.LoginResponse

	SystemUser interface {
		Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
	}

	defaultSystemUser struct {
		cli zrpc.Client
	}
)

func NewSystemUser(cli zrpc.Client) SystemUser {
	return &defaultSystemUser{
		cli: cli,
	}
}

func (m *defaultSystemUser) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	client := pb.NewSystemUserClient(m.cli.Conn())
	return client.Login(ctx, in, opts...)
}
