// Code generated by goctl. DO NOT EDIT!
// Source: monitoringManager.proto

package monitoringmanager

import (
	"context"

	"github.com/zhaoqiang0201/zero-vue-admin/server/app/rpc/monitoring/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AlertRule               = pb.AlertRule
	AlertRulePagingRequest  = pb.AlertRulePagingRequest
	AlertRulePagingResponse = pb.AlertRulePagingResponse
	Empty                   = pb.Empty

	MonitoringManager interface {
		AlertRulePaging(ctx context.Context, in *AlertRulePagingRequest, opts ...grpc.CallOption) (*AlertRulePagingResponse, error)
	}

	defaultMonitoringManager struct {
		cli zrpc.Client
	}
)

func NewMonitoringManager(cli zrpc.Client) MonitoringManager {
	return &defaultMonitoringManager{
		cli: cli,
	}
}

func (m *defaultMonitoringManager) AlertRulePaging(ctx context.Context, in *AlertRulePagingRequest, opts ...grpc.CallOption) (*AlertRulePagingResponse, error) {
	client := pb.NewMonitoringManagerClient(m.cli.Conn())
	return client.AlertRulePaging(ctx, in, opts...)
}
