// Code generated by goctl. DO NOT EDIT.
package types

type MenuMeta struct {
	Title string `json:"title"`
	Icon  string `json:"icon"`
}

type Menu struct {
	ID        int64    `json:"id"`
	ParentID  string   `json:"parentID"`
	Path      string   `json:"path"`
	Name      string   `json:"name"`
	Component string   `json:"component"`
	Meta      MenuMeta `json:"meta"`
}

type ButtonList struct {
	Name   string `json:"name"`
	Path   string `json:"path"`
	MenuID int64  `json:"menuID"`
}

type LoginRequest struct {
	UserName string `json:"userName" validate:"required"`
	PassWord string `json:"passWord" validate:"required"`
}

type LoginResponse struct {
	ID           int64  `json:"id"`
	UserName     string `json:"userName"`
	Token        string `json:"token"`
	ExpireAt     int64  `json:"expireAt"`
	RefreshAfter int64  `json:"refreshAfter"`
}

type Permission struct {
	Name       string        `json:"name"`
	MenuList   []*Menu       `json:"menuList"`
	ButtonList []*ButtonList `json:"buttonList"`
}
