// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.15.8
// source: sysuser.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SystemUserClient is the client API for SystemUser service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SystemUserClient interface {
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
	UserPermission(ctx context.Context, in *UserPermissionRequest, opts ...grpc.CallOption) (*UserPermissionResponse, error)
}

type systemUserClient struct {
	cc grpc.ClientConnInterface
}

func NewSystemUserClient(cc grpc.ClientConnInterface) SystemUserClient {
	return &systemUserClient{cc}
}

func (c *systemUserClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	out := new(LoginResponse)
	err := c.cc.Invoke(ctx, "/pb.SystemUser/Login", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *systemUserClient) UserPermission(ctx context.Context, in *UserPermissionRequest, opts ...grpc.CallOption) (*UserPermissionResponse, error) {
	out := new(UserPermissionResponse)
	err := c.cc.Invoke(ctx, "/pb.SystemUser/UserPermission", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SystemUserServer is the server API for SystemUser service.
// All implementations must embed UnimplementedSystemUserServer
// for forward compatibility
type SystemUserServer interface {
	Login(context.Context, *LoginRequest) (*LoginResponse, error)
	UserPermission(context.Context, *UserPermissionRequest) (*UserPermissionResponse, error)
	mustEmbedUnimplementedSystemUserServer()
}

// UnimplementedSystemUserServer must be embedded to have forward compatible implementations.
type UnimplementedSystemUserServer struct {
}

func (UnimplementedSystemUserServer) Login(context.Context, *LoginRequest) (*LoginResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Login not implemented")
}
func (UnimplementedSystemUserServer) UserPermission(context.Context, *UserPermissionRequest) (*UserPermissionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserPermission not implemented")
}
func (UnimplementedSystemUserServer) mustEmbedUnimplementedSystemUserServer() {}

// UnsafeSystemUserServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SystemUserServer will
// result in compilation errors.
type UnsafeSystemUserServer interface {
	mustEmbedUnimplementedSystemUserServer()
}

func RegisterSystemUserServer(s grpc.ServiceRegistrar, srv SystemUserServer) {
	s.RegisterService(&SystemUser_ServiceDesc, srv)
}

func _SystemUser_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SystemUserServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.SystemUser/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SystemUserServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SystemUser_UserPermission_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserPermissionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SystemUserServer).UserPermission(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.SystemUser/UserPermission",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SystemUserServer).UserPermission(ctx, req.(*UserPermissionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SystemUser_ServiceDesc is the grpc.ServiceDesc for SystemUser service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SystemUser_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.SystemUser",
	HandlerType: (*SystemUserServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Login",
			Handler:    _SystemUser_Login_Handler,
		},
		{
			MethodName: "UserPermission",
			Handler:    _SystemUser_UserPermission_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sysuser.proto",
}
